default:
  image: python:3.10

stages:
  - test

test_job:
  stage: test
  variables:
    DJANGO_SECRET_KEY: "secret-key-for-testing-only"
    DJANGO_DEBUG: "True"
  script:
    - echo "Starting setup..."
    - pip install -r requirements.txt
    - echo "Running tests..."
    - python manage.py test