# Generated by Django 5.2.7 on 2025-11-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_language_bookinstance_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
    ]
